/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PhNXvO0MeVM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Image from "next/image"

export function Landing() {
  return (
    (<div className="flex flex-col items-center">
      <header className="w-full pt-4 md:pt-4">
        <div className="container flex items-center justify-between px-4 md:px-6">
          <Link className="flex items-center space-x-2 text-lg font-medium" href="#">
          <Image  src="/logo.jpg" alt="Baraat" width={96} height={96} className="rounded-full border-4 border-orange-300"/>
            <h2 className="h-6 w-6" />
            Project Baraat
          </Link>
          <nav className="hidden space-x-4 text-sm font-medium md:flex">
            <Link
              className=" border-b-2 border-transparent transition-colors hover:border-gray-900 dark:hover:border-gray-50"
              href="#">
              Github
            </Link>
            <Link
              className=" border-b-2 border-transparent transition-colors hover:border-gray-900 dark:hover:border-gray-50"
              href="#">
              Huggingface
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Button size="sm" variant="outline">
              Read the Blog here
            </Button>
          </div>
        </div>
      </header>
      <main className="w-full pb-12 md:pt-4 md:pb-24">
        <section
          className="w-full bg-gray-100 border-t border-b border-gray-200 dark:bg-gray-800 dark:border-gray-800 p-12">
<div className="flex flex-col items-center justify-center">
 <div className="justify-center pb-10">
    <div >
      <CodeIcon className="w-12 mx-auto " /> {/* Adjusted margin-bottom */}
      <h1
        className="text-center text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl/line-tight lg:leading-[3.5] mb-2"> {/* Adjusted margin-bottom */}
        Introducing Baraat
      </h1>
      <p
        className="text-center text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 mb-2"> {/* Adjusted margin-bottom */}
        The large language model designed to understand and generate natural language with human-like fluency.
        Whether you need automated content creation, conversational AI, or advanced language processing,
        Baraat has you covered.
      </p>
    </div>
    <div className="pt-6 flex justify-center">
    <Button size="lg" className="mx-auto">Learn More</Button>
    </div>
 </div>
</div>
<div
 className="container flex flex-col gap-4 px-4 text-center md:gap-8 md:flex-row md:items-center md:px-6 lg:gap-12">
 <img
    alt="Image"
    className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center md:w-[1024px] lg:mr- lg:order-last border-8 border-orange-300 shadow-2xl hover:shadow-inner hover:scale-105 transition-transform duration-300"
    height="225"
    src="/baraat.png"
    width="400" />
</div>
        </section>
        {/* <section className="w-full py-12 md:py-24 lg:py-32" id="features">
          <div
            className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
            <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Powering Innovation with Advanced Language Processing
              </h2>
              <p
                className="max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Baraat offers a wide range of features and benefits for businesses, developers, and researchers working
                with natural language. Here's what makes Baraat stand out.
              </p>
            </div>
            <div
              className="grid max-w-sm gap-4 md:max-w-none md:grid-cols-3 lg:grid-cols-3xl gap-8">
              <div className="flex flex-col items-center space-y-2">
                <SquareIcon className="w-12 h-12 rounded-lg p-3 bg-gray-100 dark:bg-gray-800" />
                <h3 className="text-lg font-semibold">Semantic Understanding</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Baraat can interpret the meaning of text and understand the context of conversations.
                </p>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <TextIcon className="w-12 h-12 rounded-lg p-3 bg-gray-100 dark:bg-gray-800" />
                <h3 className="text-lg font-semibold">Conversational AI</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Developers can use Baraat to create chatbots and virtual assistants with natural language
                  capabilities.
                </p>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <SearchIcon className="w-12 h-12 rounded-lg p-3 bg-gray-100 dark:bg-gray-800" />
                <h3 className="text-lg font-semibold">Content Generation</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Baraat excels at generating human-like text for a variety of applications, from writing articles to
                  composing poetry.
                </p>
              </div>
            </div>
          </div>
        </section> */}
        {/* <section className="w-full py-12 md:py-24 lg:py-32" id="testimonials">
          <div className="container flex flex-col items-center space-y-4 px-4 md:px-6">
            <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Trusted by Users Around the World</h2>
            </div>
            <div
              className="grid max-w-sm gap-4 md:max-w-none md:grid-cols-3 lg:grid-cols-3xl gap-8">
              <div className="flex flex-col items-center space-y-2">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="120"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "120/120",
                    objectFit: "cover",
                  }}
                  width="120" />
                <blockquote
                  className="text-sm text-gray-500/70 italic text-center max-w-prose dark:text-gray-400/70">
                  "Baraat has transformed the way our customer support team interacts with clients. The language model's
                  ability to generate empathetic and accurate responses has improved customer satisfaction across the
                  board."
                </blockquote>
                <cite className="font-semibold not-italic">— Sarah Johnson, Head of Customer Experience</cite>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="120"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "120/120",
                    objectFit: "cover",
                  }}
                  width="120" />
                <blockquote
                  className="text-sm text-gray-500/70 italic text-center max-w-prose dark:text-gray-400/70">
                  "As a researcher in computational linguistics, I've experimented with various language models, and I
                  must say that Baraat stands out. Its nuanced understanding of syntax and semantics makes it a valuable
                  tool for my work."
                </blockquote>
                <cite className="font-semibold not-italic">— Dr. Alejandro Gomez, Computational Linguist</cite>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="120"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "120/120",
                    objectFit: "cover",
                  }}
                  width="120" />
                <blockquote
                  className="text-sm text-gray-500/70 italic text-center max-w-prose dark:text-gray-400/70">
                  "The language model's ability to generate empathetic and accurate responses has improved customer
                  satisfaction across the board."
                </blockquote>
                <cite className="font-semibold not-italic">— Dr. Mei Ling, AI Researcher</cite>
              </div>
            </div>
          </div>
        </section> */}
      </main>
      <footer className="w-full border-t">
        <div
          className="container flex flex-col items-center justify-center py-4 md:py-6 space-y-4 px-4 md:px-6">
          <div className="flex flex-col items-center space-y-2 text-center">
            <h3 className="text-lg font-semibold">Sign up for updates</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Stay informed about the latest developments in language technology.
            </p>
          </div>
          <form
            className="flex flex-col gap-4 md:flex-row md:items-center md:gap-2 lg:gap-4">
            <Input
              className="max-w-sm md:w-[300px]"
              placeholder="Enter your email"
              type="email" />
            <Button className="md:ml-2" size="lg">
              Subscribe
            </Button>
          </form>
          <div
            className="flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400">
            <span>© 2024 Baraat. All rights reserved.</span>
            <Link className="underline underline-offset-2" href="#">
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function SquareIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>)
  );
}


function TextIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>)
  );
}
